project:
  type: website
  resources: assets

website:
  title: "Payson Johanson"
  navbar: 
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
    right: 
      - icon: github
        href: https://www.github.com/
        target: blank
      - icon: file-pdf
        href: assets/Resume_2025.pdf
        target: blank
format:
  html:
    theme:
      light: sandstone
      dark: slate
    css: styles.css
    toc: true

execute: 
  freeze: auto

