project:
  type: website
  resources: assets

website:
  title: "Payson Johanson"
  navbar: 
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
      - href: assets/Resume_2025.pdf
        text: Resume
    right: 
      - icon: github
        href: https://www.github.com/
        target: blank
format:
  html:
    theme:
      - custom.scss
    css: styles.css
    toc: true

execute:
  freeze: auto